plugins {
    id 'java-library'
    id 'java-test-fixtures'
    id 'jacoco'
    alias(syncLibs.plugins.kotlin.jvm)
    alias(syncLibs.plugins.kotlin.kapt)
    alias(syncLibs.plugins.protobuf)
    alias(syncLibs.plugins.buildconfig)
    alias(syncLibs.plugins.sqldelight)
    id 'org.gradle.idea'
}

repositories {
    google()
    mavenCentral()
}

group = 'eu.pretix.pretixdesk'
version = '1.0'

compileJava.options.encoding = 'UTF-8'
compileTestJava.options.encoding = 'UTF-8'

buildConfig {
    className('BuildConfig')
    packageName('eu.pretix.libpretixsync')
    useJavaOutput()

    buildConfigField(String, 'DB', 'sqlite')
    buildConfigField(String, 'BOOLEAN_TYPE', 'NUMERIC')
    buildConfigField(String, 'BOOLEAN_FALSE', '0')
}

kotlin {
    jvmToolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}
java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11

    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}

idea {
    module {
        sourceDirs += compileJava.options.generatedSourceOutputDirectory.getAsFile().getOrNull()
        generatedSourceDirs += compileJava.options.generatedSourceOutputDirectory.getAsFile().getOrNull()
        testSources.from(compileTestJava.options.generatedSourceOutputDirectory.getAsFile().getOrNull())
        generatedSourceDirs += compileTestJava.options.generatedSourceOutputDirectory.getAsFile().getOrNull()
    }
}

configurations {
    maybeCreate("compile")
}

jacoco {
    toolVersion = "0.8.7"
}

jacocoTestReport {
    reports {
        xml.required = true
        html.required = true
    }
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${syncLibs.versions.protobuf.get()}"
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                java {
                    option "lite"
                }
            }
        }
    }
}

check.dependsOn jacocoTestReport

dependencies {
    implementation syncLibs.okhttp
    testFixturesImplementation syncLibs.okhttp
    implementation syncLibs.joda.time

    implementation syncLibs.json
    testFixturesImplementation syncLibs.json

    implementation syncLibs.streamsupport.cfuture
    implementation syncLibs.jackson.databind
    implementation syncLibs.jackson.moduleKotlin

    implementation syncLibs.javax.annotation
    implementation syncLibs.eddsa
    implementation syncLibs.protobuf.javalite

    implementation syncLibs.sqldelight.sqlite.driver

    annotationProcessor syncLibs.jsr250

    testFixturesImplementation syncLibs.junit
    testFixturesImplementation syncLibs.sqlite.jdbc
    testImplementation syncLibs.junit
    testImplementation syncLibs.sqlite.jdbc
}

tasks.register('copyTestResources', Copy) {
    from "${projectDir}/src/test/resources", "${projectDir}/src/main/resources"
    into layout.buildDirectory.dir("classes/test")
}
processTestResources.dependsOn copyTestResources

sqldelight {
    databases {
        SyncDatabase {
            packageName = "eu.pretix.libpretixsync.sqldelight"
            srcDirs('src/main/sqldelight/sqlite', 'src/main/sqldelight/common', 'src/main/sqldelight/migrations')

            // SQLDelight supports migration validation by running the migrations against a database file from a
            // previous version and comparing the result against the current schema.
            //
            // The database dumps can be generated with the Gradle task `generateMainSyncDatabaseSchema`, which will
            // place a .db file in `schemaOutputDirectory` (e.g. 100.db for schema version 100).
            //
            // Unfortunately, the validation is buggy for complex schemas (see https://github.com/sqldelight/sqldelight/issues/4759)
            // and will hang or run out of memory in the current release.
            //
            // Running the `verifyMainSyncDatabaseMigration` is still helpful to check the syntax of the migrations.
            schemaOutputDirectory.set(file("src/main/sqldelight/sqlite"))


            // Oldest dialect supported by SQLDelight 2.1.0
            // In Android projects, it will auto-select based on SDK
            // but not go lower than 3.18 (Android 9 is still on 3.8)
            dialect "app.cash.sqldelight:sqlite-3-18-dialect:${syncLibs.versions.sqldelight.get()}"
        }
    }
}
