import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id 'java-library'
    id 'java-test-fixtures'
    id 'jacoco'
    alias(syncLibs.plugins.kotlin.jvm)
    alias(syncLibs.plugins.kotlin.kapt)
    alias(syncLibs.plugins.protobuf)
    alias(syncLibs.plugins.buildconfig)
    alias(syncLibs.plugins.sqldelight)
    id 'org.gradle.idea'
}

repositories {
    google()
    mavenCentral()
}

group = 'eu.pretix.pretixdesk'
version = '1.0'

buildConfig {
    className('BuildConfig')
    packageName('eu.pretix.libpretixsync')
    useJavaOutput()

    buildConfigField(String, 'DB', 'postgres')
    buildConfigField(String, 'BOOLEAN_TYPE', 'boolean')
    buildConfigField(String, 'BOOLEAN_FALSE', 'false')
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

idea {
    module {
        sourceDirs += compileJava.options.generatedSourceOutputDirectory.getAsFile().getOrNull()
        generatedSourceDirs += compileJava.options.generatedSourceOutputDirectory.getAsFile().getOrNull()
        testSources.from(compileTestJava.options.generatedSourceOutputDirectory.getAsFile().getOrNull())
        generatedSourceDirs += compileTestJava.options.generatedSourceOutputDirectory.getAsFile().getOrNull()
    }
}

repositories {
    mavenCentral()
}

configurations {
    maybeCreate("compile")
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_11
    }
}

jacoco {
    toolVersion = "0.8.7"
}

jacocoTestReport {
    reports {
        xml.required = true
        html.required = true
    }
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${syncLibs.versions.protobuf.get()}"
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                java {
                    option "lite"
                }
            }
        }
    }
}

check.dependsOn jacocoTestReport

dependencies {
    implementation syncLibs.okhttp
    testFixturesImplementation syncLibs.okhttp
    implementation syncLibs.joda.time

    implementation syncLibs.json
    testFixturesImplementation syncLibs.json

    implementation syncLibs.streamsupport.cfuture
    implementation syncLibs.jackson.databind
    implementation syncLibs.jackson.moduleKotlin

    implementation syncLibs.javax.annotation
    implementation syncLibs.eddsa
    implementation syncLibs.protobuf.javalite

    implementation syncLibs.sqldelight.sqlite.driver

    annotationProcessor syncLibs.jsr250

    testFixturesImplementation syncLibs.junit
    testFixturesImplementation syncLibs.sqlite.jdbc
    testImplementation syncLibs.junit
    testImplementation syncLibs.sqlite.jdbc
}

tasks.register('copyTestResources', Copy) {
    from "${projectDir}/src/test/resources", "${projectDir}/src/main/resources"
    into layout.buildDirectory.dir("classes/test")
}
processTestResources.dependsOn copyTestResources

sqldelight {
    databases {
        SyncDatabase {
            packageName = "eu.pretix.libpretixsync.sqldelight"
            dialect "app.cash.sqldelight:postgresql-dialect:${syncLibs.versions.sqldelight.get()}"
            srcDirs('src/main/sqldelight/postgres', 'src/main/sqldelight/common', 'src/main/sqldelight/migrations')
        }
    }
}
