pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        maven {
            url = "https://plugins.gradle.org/m2/"
        }
    }
}

dependencyResolutionManagement {
    versionCatalogs {
        syncLibs {
            from(files("gradle/libs.versions.toml"))
        }
    }
}

rootProject.name = 'eu.pretix.libpretixsync'
