package eu.pretix.libpretixsync.utils

fun cleanInput(raw_input: String, source_type: String): String {
    var cleaned = raw_input.replace(Regex("[\\p{C}]"), "�")  // remove unprintable characters
    if (source_type == "barcode") {
        // Remove ECI flag which is prepended by some barcode scanners to QR codes generated by the
        // app "WalletPasses" (and recently even Google Wallet) even though it is the default encoding.
        // https://en.wikipedia.org/wiki/Extended_Channel_Interpretation
        cleaned = cleaned
            .removePrefix("\\000001")  // Latin1
            .removePrefix("\\000003")  // Latin1
            .removePrefix("\\000026")  // UTF-8
            .removePrefix("\\000027")  // ASCII
    }
    return cleaned
}