package eu.pretix.libpretixsync.sqldelight

import app.cash.sqldelight.ColumnAdapter
import java.time.LocalDate
import java.time.ZoneId
import java.util.Date

class PostgresJavaUtilDateAdapter : ColumnAdapter<Date, LocalDate> {

    override fun decode(databaseValue: LocalDate): Date {
        // The columns generated by requery do not contain time information.
        // As a workaround, assume midnight.
        //
        // Once the data is no longer accessed by requery, the columns should be migrated
        // to a data type with a time portion.
        return Date.from(databaseValue.atStartOfDay(ZoneId.of("UTC")).toInstant())
    }

    override fun encode(value: Date): LocalDate {
        return value.toInstant().atZone(ZoneId.of("UTC")).toLocalDate()
    }
}
